adding ecs clusters comparison and sendto functionality
Signiant/Jarvis pull request #4
Opened 2017-06-21 15:45 UTC by farque65

2017-06-21 16:34 UTC, haggaret commented
General comment - it was taking me way too long to figure out what certain functions were trying to do. Comments and better variable/parameter names would go a LONG way to explaining the code.

2017-06-21 16:34 UTC, haggaret reviewed
General comment - it was taking me way too long to figure out what certain functions were trying to do. Comments and better variable/parameter names would go a LONG way to explaining the code.

2017-06-21 16:34 UTC, haggaret commented on src/lambda_function.py
> +    else:
Do you want to print locally what you're sending to the other channel as well? Not sure if that makes sense or not...but perhaps an option

2017-06-21 16:34 UTC, haggaret commented on src/plugins/ecs/__init__.py
> +															  config["General"]["script_tags"]["ending_tag"])
Did you mean to have this huge space before these arguments?

2017-06-21 16:34 UTC, haggaret commented on src/plugins/ecs/__init__.py
> +															team_data,
Same question here about the spaces before these arguments

2017-06-21 16:34 UTC, haggaret commented on src/plugins/ecs/__init__.py
> +	if result.has_key('environment_code_name') == False:
I've never used this - I've always just done, "if 'environment_code_name' in result:", but good to know there is an alternative.

2017-06-21 16:34 UTC, haggaret commented on src/plugins/ecs/__init__.py
> +
I'm always a fan of comments in code. You could say what you're doing in the following for loop - what you're trying to get. I'm not completely clear on what you're trying to do here. Better variable/parameter names might help.

2017-06-21 16:34 UTC, haggaret commented on src/plugins/ecs/ecs_compares.py
> +
Did you mean to leave this print statement in here? If so, do you want to preface it with something that tells the user what is being printed?

2017-06-21 16:34 UTC, haggaret commented on src/plugins/ecs/ecs_compares.py
> +					break
This is cool - didn't know you could do this!

2017-06-21 16:34 UTC, haggaret commented on src/plugins/ecs/ecs_compares.py
> +
Again, parameter names are a bit vague - what is j_tags?

2017-06-21 16:34 UTC, haggaret commented on src/plugins/ecs/ecs_compares.py
> +	res = list(set(compareto) ^ set(lookup))
Comments - what does this do?

2017-06-21 17:14 UTC, dnorth98 requested changes
Just a few changes, mostly around comments

2017-06-21 17:14 UTC, dnorth98 commented on src/lambda_function.py
> +    if "sendto:" in text:
Did we update the help to include the fact you can now sendto a channel?  I assume this is generic now to all commands?

2017-06-21 17:14 UTC, dnorth98 commented on src/plugins/ecs/__init__.py
> +	jarvis ecs compare <cluster> [in <region> <account>] against <cluster> [in <region> <account>]"""
Would we use "with" instead of "against"?  Nit-picky I know....

2017-06-21 17:14 UTC, dnorth98 commented on src/plugins/ecs/__init__.py
> +                cached_items = items.replace(beginning_script_tag, "").replace(ending_script_tag, "")
One thing we will need to check now that we are caching is the memory allocation on the lambda function.  Lambda functions have a max execution time and a memory limit.  It's probably ok but worth reviewing what it is given we are caching the superjenkins response now

2017-06-21 17:14 UTC, dnorth98 commented on src/plugins/ecs/__init__.py
> +	if len(result) <= 3:
Comment would be good here...when is the len less than 3?

2017-06-21 17:14 UTC, dnorth98 commented on src/plugins/ecs/__init__.py
> +				return 4
Couldn't we just return len(args)?

2017-06-21 17:14 UTC, dnorth98 commented on src/plugins/ecs/ecs_compares.py
> +					break
Roles FTW!

2017-06-21 17:14 UTC, dnorth98 commented on src/plugins/ecs/ecs_compares.py
> +def finalize_service_name(service_name, service_def, environment_code_name):
A comment on the purpose of this function would be handy (I kinda agree with Kev on this generically - the WHAT isn't important in comments, it's the WHY)

2017-06-21 17:14 UTC, dnorth98 commented on src/plugins/ecs/ecs_compares.py
> +																	  t_array['service_definition'],
indent is off here and just below

2017-06-21 17:41 UTC, haggaret commented on src/plugins/ecs/__init__.py
> +                cached_items = items.replace(beginning_script_tag, "").replace(ending_script_tag, "")
Problem: Superjenkins is only available within our network - not accessible by an AWS lambda function

2017-06-21 17:45 UTC, haggaret commented on src/plugins/ecs/__init__.py
> +
What is the for loop below trying to accomplish? Comments would help...

2017-06-22 17:20 UTC, haggaret commented on src/compare_output/__init__.py
> +def form_the_time(thetime):
nit picky - why not format_the_time or format_time instead of form_...?  :)

2017-06-22 17:21 UTC, haggaret commented on src/compare_output/__init__.py
> +#compress string is larger than 30 length
compress string *if* longer than?

2017-06-22 17:26 UTC, haggaret commented on src/plugins/ecs/__init__.py
> +
I'm still not clear on what the for loop is trying to accomplish . :)

2017-06-22 17:28 UTC, haggaret commented on src/plugins/ecs/ecs_compares.py
> +	if jenkin_build_terms[0] in master_env or jenkin_build_terms[1] in master_env:
Will there always be 2 elements in jenkin_build_terms?

2017-06-22 17:30 UTC, haggaret commented on src/plugins/ecs/ecs_compares.py
> +																		m_data['service_definition'],
What is up with the huge white space at the beginning of this line, and the next - also down below...

2017-06-22 17:31 UTC, haggaret approved these changes

2017-06-22 17:45 UTC, merged